spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: emiw2003
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: texnoera.academy@gmail.com
    password: sjqmzjnzbyxxlusr
    port: 587
  jpa:
    hibernate:
      ddl-auto: update
